# Credenciales de Neon
spring.datasource.url=jdbc:postgresql://ep-dry-sun-am3k3lhs-pooler.c-5.us-east-1.aws.neon.tech/QueBoleta%21?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_z7KFmLkpidn9

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de logs para ver errores de conexión
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuración de reservas (RQ-02)
tiempoReserva=24